export const TOOL_CALL_STATES = Object.freeze({
  PLANNED: "planned",
  PREPARED: "prepared",
  DISPATCHED: "dispatched",
  EFFECT_CONFIRMED: "effect_confirmed",
  RECEIPT_STORED: "receipt_stored",
  REPORTED: "reported",
  FAILED: "failed",
  CANCEL_REQUESTED: "cancel_requested",
  CANCELLED: "cancelled",
  UNKNOWN: "unknown",
  NEEDS_RECONCILIATION: "needs_reconciliation",
  NEEDS_CONFIRMATION: "needs_confirmation"
});

const TRANSITIONS = new Map([
  [TOOL_CALL_STATES.PLANNED, new Set([
    TOOL_CALL_STATES.PREPARED,
    TOOL_CALL_STATES.FAILED,
    TOOL_CALL_STATES.CANCELLED
  ])],
  [TOOL_CALL_STATES.PREPARED, new Set([
    TOOL_CALL_STATES.DISPATCHED,
    TOOL_CALL_STATES.FAILED,
    TOOL_CALL_STATES.CANCELLED,
    TOOL_CALL_STATES.NEEDS_CONFIRMATION,
    TOOL_CALL_STATES.NEEDS_RECONCILIATION
  ])],
  [TOOL_CALL_STATES.DISPATCHED, new Set([
    TOOL_CALL_STATES.EFFECT_CONFIRMED,
    TOOL_CALL_STATES.RECEIPT_STORED,
    TOOL_CALL_STATES.FAILED,
    TOOL_CALL_STATES.CANCEL_REQUESTED,
    TOOL_CALL_STATES.UNKNOWN,
    TOOL_CALL_STATES.NEEDS_RECONCILIATION,
    TOOL_CALL_STATES.NEEDS_CONFIRMATION
  ])],
  [TOOL_CALL_STATES.CANCEL_REQUESTED, new Set([
    TOOL_CALL_STATES.CANCELLED,
    TOOL_CALL_STATES.UNKNOWN,
    TOOL_CALL_STATES.NEEDS_RECONCILIATION,
    TOOL_CALL_STATES.NEEDS_CONFIRMATION,
    TOOL_CALL_STATES.RECEIPT_STORED
  ])],
  [TOOL_CALL_STATES.EFFECT_CONFIRMED, new Set([
    TOOL_CALL_STATES.RECEIPT_STORED,
    TOOL_CALL_STATES.UNKNOWN,
    TOOL_CALL_STATES.NEEDS_RECONCILIATION
  ])],
  [TOOL_CALL_STATES.RECEIPT_STORED, new Set([
    TOOL_CALL_STATES.REPORTED
  ])],
  [TOOL_CALL_STATES.UNKNOWN, new Set([
    TOOL_CALL_STATES.RECEIPT_STORED,
    TOOL_CALL_STATES.NEEDS_RECONCILIATION,
    TOOL_CALL_STATES.NEEDS_CONFIRMATION,
    TOOL_CALL_STATES.FAILED,
    TOOL_CALL_STATES.CANCELLED
  ])],
  [TOOL_CALL_STATES.NEEDS_RECONCILIATION, new Set([
    TOOL_CALL_STATES.PREPARED,
    TOOL_CALL_STATES.RECEIPT_STORED,
    TOOL_CALL_STATES.NEEDS_CONFIRMATION,
    TOOL_CALL_STATES.FAILED,
    TOOL_CALL_STATES.CANCELLED,
    TOOL_CALL_STATES.DISPATCHED
  ])],
  [TOOL_CALL_STATES.NEEDS_CONFIRMATION, new Set([
    TOOL_CALL_STATES.PREPARED,
    TOOL_CALL_STATES.DISPATCHED,
    TOOL_CALL_STATES.CANCELLED,
    TOOL_CALL_STATES.FAILED,
    TOOL_CALL_STATES.RECEIPT_STORED
  ])]
]);

const TERMINAL = new Set([
  TOOL_CALL_STATES.REPORTED,
  TOOL_CALL_STATES.FAILED,
  TOOL_CALL_STATES.CANCELLED
]);

export function canTransitionToolCall(from, to) {
  if (!from || from === to) {
    return true;
  }

  return TRANSITIONS.get(from)?.has(to) === true;
}

export function assertToolCallTransition(from, to) {
  if (!canTransitionToolCall(from, to)) {
    throw new Error(`Invalid Tool call transition: ${from} -> ${to}`);
  }
}

export function isTerminalToolCallState(state) {
  return TERMINAL.has(state);
}
